"""Add Gejala

Revision ID: 4d6fe6565126
Revises: 767d3274caca
Create Date: 2026-01-23 13:46:19.755834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6fe6565126'
down_revision = '767d3274caca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode'),
    sa.UniqueConstraint('nama')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gejala')
    # ### end Alembic commands ###
