"""add diagnosa

Revision ID: 50fe50bc125d
Revises: fe30fd596b6e
Create Date: 2026-01-29 12:43:41.266120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fe50bc125d'
down_revision = 'fe30fd596b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
