"""update Penyakit

Revision ID: 618ed31b06c4
Revises: 79d38cb52f9f
Create Date: 2026-01-26 17:08:17.355365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618ed31b06c4'
down_revision = '79d38cb52f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bobot', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.drop_column('bobot')

    # ### end Alembic commands ###
