"""Add Penyakit

Revision ID: 79d38cb52f9f
Revises: 4d6fe6565126
Create Date: 2026-01-26 17:06:51.393276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d38cb52f9f'
down_revision = '4d6fe6565126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penyakit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('solusi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('aturan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penyakit_id', sa.Integer(), nullable=False),
    sa.Column('gejala_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gejala_id'], ['gejala.id'], ),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aturan')
    op.drop_table('penyakit')
    # ### end Alembic commands ###
